//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModelFirst.Models.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Albums
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AlbumArtUrl { get; set; }
        public string ReleaseDate { get; set; }
    
        public virtual Genres Genre { get; set; }
        public virtual Artists Artist { get; set; }
    }
}
