//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDaybook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daybook_order
    {
        public int Id { get; set; }
        public double s_price { get; set; }
        public long quantity { get; set; }
        public string name { get; set; }
        public int ProductId { get; set; }
        public int Daybook_lineId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Daybook_line Daybook_line { get; set; }
    }
}
