//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDaybook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daybook_line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Daybook_line()
        {
            this.Daybook_order = new HashSet<Daybook_order>();
        }
    
        public int Id { get; set; }
        public double total { get; set; }
        public System.DateTime date { get; set; }
        public int DaybookId { get; set; }
    
        public virtual Daybook Daybook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daybook_order> Daybook_order { get; set; }
    }
}
