//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcDaybook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.min_quantity = 0;
            this.Daybook_order = new HashSet<Daybook_order>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public string photo { get; set; }
        public long quantity { get; set; }
        public Nullable<long> min_quantity { get; set; }
        public double price { get; set; }
        public long code { get; set; }
        public double purchase_price { get; set; }
        public string warranty { get; set; }
        public string description { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daybook_order> Daybook_order { get; set; }
    }
}
